/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AchievementType = { 'five_referrals' : null } |
  { 'kyc_verified' : null } |
  { 'ten_k_invested' : null } |
  { 'ten_spins' : null } |
  { 'profile_complete' : null } |
  { 'first_withdrawal' : null } |
  { 'first_deposit' : null };
export type KycDocumentType = { 'pan' : null } |
  { 'aadhaar' : null };
export type KycStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface LoginActivity {
  'deviceDetails' : string,
  'provider' : string,
  'user' : Principal,
  'timestamp' : bigint,
  'ipAddress' : string,
}
export type PaymentStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface PaymentSubmission {
  'utr' : string,
  'status' : PaymentStatus,
  'paymentMethod' : string,
  'screenshotBlobId' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface PortfolioEntry { 'coin' : string, 'amount' : number }
export interface SupportTicket {
  'status' : TicketStatus,
  'subject' : string,
  'owner' : Principal,
  'ticketId' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'replies' : Array<TicketReply>,
}
export interface TicketReply {
  'sender' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export type TicketStatus = { 'closed' : null } |
  { 'open' : null };
export interface UserProfile {
  'portfolio' : Array<PortfolioEntry>,
  'referralCode' : string,
  'referred' : Array<Principal>,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VipTier = { 'bronze' : null } |
  { 'gold' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export interface VipTierInfo {
  'tier' : VipTier,
  'totalVerifiedDeposits' : number,
}
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'coin' : string,
  'address' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export type WithdrawalStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyStock' : ActorMethod<[bigint], undefined>,
  'closeTicket' : ActorMethod<[bigint], undefined>,
  'createPriceAlert' : ActorMethod<[string, number, bigint], bigint>,
  'createReferralCode' : ActorMethod<[string], undefined>,
  'createStockPlan' : ActorMethod<
    [string, number, number, number, string, bigint],
    bigint
  >,
  'deletePriceAlert' : ActorMethod<[bigint], undefined>,
  'getAllPayments' : ActorMethod<
    [],
    Array<[Principal, Array<PaymentSubmission>]>
  >,
  'getAllTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getAllWithdrawals' : ActorMethod<
    [],
    Array<[Principal, Array<WithdrawalRequest>]>
  >,
  'getBalance' : ActorMethod<[Principal], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKycStatus' : ActorMethod<[], KycStatus>,
  'getLastLogins' : ActorMethod<[], Array<LoginActivity>>,
  'getUserBalance' : ActorMethod<[], number>,
  'getUserPayments' : ActorMethod<[], Array<PaymentSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getUserWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getVipTier' : ActorMethod<[], VipTierInfo>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordLoginActivity' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'registerReferral' : ActorMethod<[string], undefined>,
  'replyToTicket' : ActorMethod<[bigint, string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitKyc' : ActorMethod<
    [KycDocumentType, string, string, string, bigint],
    undefined
  >,
  'submitPayment' : ActorMethod<
    [string, number, string, string, bigint],
    undefined
  >,
  'submitSupportTicket' : ActorMethod<[string, string, bigint], bigint>,
  'submitWithdrawalRequest' : ActorMethod<
    [number, string, string, bigint],
    undefined
  >,
  'unlockAchievement' : ActorMethod<[AchievementType, bigint], undefined>,
  'updateKycStatus' : ActorMethod<[Principal, KycStatus, string], undefined>,
  'updatePaymentStatus' : ActorMethod<
    [Principal, string, PaymentStatus],
    undefined
  >,
  'updatePortfolio' : ActorMethod<[string, number], undefined>,
  'updateWithdrawalStatus' : ActorMethod<
    [Principal, bigint, WithdrawalStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];