/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentSubmission = IDL.Record({
  'utr' : IDL.Text,
  'status' : PaymentStatus,
  'paymentMethod' : IDL.Text,
  'screenshotBlobId' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const TicketStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const TicketReply = IDL.Record({
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const SupportTicket = IDL.Record({
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'owner' : IDL.Principal,
  'ticketId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'replies' : IDL.Vec(TicketReply),
});
export const WithdrawalStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalStatus,
  'coin' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const PortfolioEntry = IDL.Record({
  'coin' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'portfolio' : IDL.Vec(PortfolioEntry),
  'referralCode' : IDL.Text,
  'referred' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
});
export const KycStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LoginActivity = IDL.Record({
  'deviceDetails' : IDL.Text,
  'provider' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Nat,
  'ipAddress' : IDL.Text,
});
export const VipTier = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const VipTierInfo = IDL.Record({
  'tier' : VipTier,
  'totalVerifiedDeposits' : IDL.Float64,
});
export const KycDocumentType = IDL.Variant({
  'pan' : IDL.Null,
  'aadhaar' : IDL.Null,
});
export const AchievementType = IDL.Variant({
  'five_referrals' : IDL.Null,
  'kyc_verified' : IDL.Null,
  'ten_k_invested' : IDL.Null,
  'ten_spins' : IDL.Null,
  'profile_complete' : IDL.Null,
  'first_withdrawal' : IDL.Null,
  'first_deposit' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyStock' : IDL.Func([IDL.Nat], [], []),
  'closeTicket' : IDL.Func([IDL.Nat], [], []),
  'createPriceAlert' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createReferralCode' : IDL.Func([IDL.Text], [], []),
  'createStockPlan' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deletePriceAlert' : IDL.Func([IDL.Nat], [], []),
  'getAllPayments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PaymentSubmission)))],
      ['query'],
    ),
  'getAllTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getAllWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(WithdrawalRequest)))],
      ['query'],
    ),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKycStatus' : IDL.Func([], [KycStatus], ['query']),
  'getLastLogins' : IDL.Func([], [IDL.Vec(LoginActivity)], ['query']),
  'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserPayments' : IDL.Func([], [IDL.Vec(PaymentSubmission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getUserWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getVipTier' : IDL.Func([], [VipTierInfo], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordLoginActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'registerReferral' : IDL.Func([IDL.Text], [], []),
  'replyToTicket' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitKyc' : IDL.Func(
      [KycDocumentType, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'submitPayment' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'submitSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'unlockAchievement' : IDL.Func([AchievementType, IDL.Nat], [], []),
  'updateKycStatus' : IDL.Func([IDL.Principal, KycStatus, IDL.Text], [], []),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Principal, IDL.Text, PaymentStatus],
      [],
      [],
    ),
  'updatePortfolio' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateWithdrawalStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, WithdrawalStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentSubmission = IDL.Record({
    'utr' : IDL.Text,
    'status' : PaymentStatus,
    'paymentMethod' : IDL.Text,
    'screenshotBlobId' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const TicketStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const TicketReply = IDL.Record({
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const SupportTicket = IDL.Record({
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'owner' : IDL.Principal,
    'ticketId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'replies' : IDL.Vec(TicketReply),
  });
  const WithdrawalStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalStatus,
    'coin' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const PortfolioEntry = IDL.Record({
    'coin' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'portfolio' : IDL.Vec(PortfolioEntry),
    'referralCode' : IDL.Text,
    'referred' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
  });
  const KycStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LoginActivity = IDL.Record({
    'deviceDetails' : IDL.Text,
    'provider' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Nat,
    'ipAddress' : IDL.Text,
  });
  const VipTier = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const VipTierInfo = IDL.Record({
    'tier' : VipTier,
    'totalVerifiedDeposits' : IDL.Float64,
  });
  const KycDocumentType = IDL.Variant({
    'pan' : IDL.Null,
    'aadhaar' : IDL.Null,
  });
  const AchievementType = IDL.Variant({
    'five_referrals' : IDL.Null,
    'kyc_verified' : IDL.Null,
    'ten_k_invested' : IDL.Null,
    'ten_spins' : IDL.Null,
    'profile_complete' : IDL.Null,
    'first_withdrawal' : IDL.Null,
    'first_deposit' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyStock' : IDL.Func([IDL.Nat], [], []),
    'closeTicket' : IDL.Func([IDL.Nat], [], []),
    'createPriceAlert' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createReferralCode' : IDL.Func([IDL.Text], [], []),
    'createStockPlan' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deletePriceAlert' : IDL.Func([IDL.Nat], [], []),
    'getAllPayments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PaymentSubmission)))],
        ['query'],
      ),
    'getAllTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getAllWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(WithdrawalRequest)))],
        ['query'],
      ),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKycStatus' : IDL.Func([], [KycStatus], ['query']),
    'getLastLogins' : IDL.Func([], [IDL.Vec(LoginActivity)], ['query']),
    'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserPayments' : IDL.Func([], [IDL.Vec(PaymentSubmission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getUserWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getVipTier' : IDL.Func([], [VipTierInfo], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordLoginActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'registerReferral' : IDL.Func([IDL.Text], [], []),
    'replyToTicket' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitKyc' : IDL.Func(
        [KycDocumentType, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'submitPayment' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'submitSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'unlockAchievement' : IDL.Func([AchievementType, IDL.Nat], [], []),
    'updateKycStatus' : IDL.Func([IDL.Principal, KycStatus, IDL.Text], [], []),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Principal, IDL.Text, PaymentStatus],
        [],
        [],
      ),
    'updatePortfolio' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateWithdrawalStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, WithdrawalStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };